# Generated by Django 4.2.6 on 2023-11-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionaria', '0002_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/'),
        ),
    ]
